### ISSUE TITLE
A few ideas etc.

### ISSUE THREAD

**Issue by MisterLolxd2** [MathiasMC/PvPLevels#5]
I see you back when, welcome back.
I back to with my suggestion/bugs: 
1. Old (but still exist) https://pastebin.com/E1BzKWzL
2. [22:57:42 WARN]: [PvPLevels] Version: 2.2.4 has been released! you are currently using version: 2.2.5
3. Im really not get how to works now: https://pastebin.com/KzCA2e1S
I using before update this method: https://pastebin.com/pdBV8dMV
4. Optimization problem with the database. I see the code etc. The problem is: You dont store the nickname to database, only UUID and next you convert this UUID to nickname, with TOPS its problem, the problem is bigger than you base have MANY OF RECORD, it does not cause unknown lag, but over time it simply lowers TPS, which makes it less stable. If database bigger that the "unstable tps" is easy to see. 
5. Can you add command to edit/reset/check stats for offline players?

**Comment by MathiasMC** [comment]
Thanks

1. You can delete the deaths command in the config that will turn it off if thats what you mean?

2. Is fixed just takes some time

3. In your case https://pastebin.com/MbaE7WLQ

4 & 5. I will look into that

**Comment by MisterLolxd2** [comment]
1. Yes.

Thanks.

**Comment by kassadGLA** [comment]
I have a question about point 4.
What's the point of saving a nickname if a player can change it?

**Comment by MathiasMC** [comment]
> I have a question about point 4. What's the point of saving a nickname if a player can change it?

It's more efficient to save nickname on login instead of converting uuid to name every time top stats update

**Comment by MisterLolxd2** [comment]
> I have a question about point 4. What's the point of saving a nickname if a player can change it?

In my case, my server is non-premium. Still, converting every time you update, for example, the top 10 killers in a database that has a lot of stored data, in a sense burdens.

**Comment by MathiasMC** [comment]
> > I have a question about point 4. What's the point of saving a nickname if a player can change it?
> 
> 
> 
> In my case, my server is non-premium. Still, converting every time you update, for example, the top 10 killers in a database that has a lot of stored data, in a sense burdens.

In the next update it will be fixed.
In a few days (next version)

**Comment by MisterLolxd2** [comment]
Thank you some much<3.

**Comment by MathiasMC** [comment]
> Thank you some much<3.

Hey Do you have discord can you add me i just want to ask you something? mathiasmc

**Comment by MisterLolxd2** [comment]
I have another idea: Can you add option to prevent killing player with this same ip? To prevent farming killing on another accounts?

**Comment by MathiasMC** [comment]
> I have another idea: Can you add option to prevent killing player with this same ip? To prevent farming killing on another accounts? 

Already added is that what you mean? Killsession in config.yml
Next update take a little bit longer but will release it as soon as i can :)

**Comment by MisterLolxd2** [comment]
This solution is global. For example, I would like to completely disable the possibility of counting homicides, etc. people who have the same IP address. If attacker's ip its same like victim's ip the kills/rewards etc. cannot be added.

**Comment by MisterLolxd2** [comment]
[00:06:56] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'PvPLevels 2.2.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.2
	at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:382) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	PVPlevels died in 1.19.4

**Comment by MathiasMC** [comment]
Just updated PvPLevels with a quick fix for that
